### ISSUE TITLE
Improve error handling in api.go

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#106]
We need to manage the bubbling up of multiple errors better. Most API methods have the propensity of having two errors to return at the end of the method: an error internal to the method itself and an error returned by a call out to a proxy client if there was an internal error. Right now we give precedence to the internal errors, but it would be better to track both (in `[]error`), and on return concatenate both messages and return a composite error. 

Additionally, for the the `eth_call` method, we have two more potential errors to track: the `newRevertError` and  the `result.Err`. In this case it would be particularly helpful to expose all these errors, of which all 4 could potentially occur in a single call.

See https://github.com/vulcanize/ipld-eth-server/pull/105#discussion_r719370160

**Comment by AFDudley** [comment]
@dboreham @telackey If this has been resolved please close.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-server/issues/106
