### ISSUE TITLE
Clean up proxy RPC call code in api.go

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#107]
This is somewhat related to #106. These methods, particularly `eth_call`, are very busy and we can probably clean up our approach for calling out to the proxy RPC client when an internal error occurs.

**Comment by AFDudley** [comment]
@dboreham @telackey Please close if resolved. Thank you.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-server/issues/107
