### ISSUE TITLE
Invoke eth-statediff-service cluster to fill missing blocks

### ISSUE THREAD

**Issue by ashwinphatak** [cerc-io/ipld-eth-server#130]
Invoke an eth-statediff cluster to fill missing block(s) when a RPC call to ipld-eth-server fails, instead of calling out to geth.

**Comment by AFDudley** [comment]
This should leverage k8s.
It should also be used in the trace generation system.

**Comment by AFDudley** [comment]
Resolved with https://github.com/cerc-io/chain-chunker
