### ISSUE TITLE
Persist canonical header references for quick lookup

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#14]
`canoncial_header()` function introduced in #11 can find the canonical header based on the weight in the database, but it is a iterative function that is prohibitively expensive for serving request on-the-fly for headers that are far removed from the current head.

We need to create a trigger function that watches for inserts at the head (`n`) and uses `canoncial_header()` to derive and caches the canonical header (or rather a reference to it) for block `n - x`, where `x` can be adjusted (start with a default of 2048).

**Comment by i-norden** [comment]
In the meantime, #25 and #26 have heuristically optimized the canonical_header function

**Comment by Burmenska** [comment]
@stellarmagnet should we keep this task open? the last update on it was more than 6 months ago
