### ISSUE TITLE
Cleanup legacy graphql API

### ISSUE THREAD

**Issue by ashwinphatak** [cerc-io/ipld-eth-server#150]
* Clean legacy graphql API methods which are no longer used
* Support ipld-eth-client API surface (related https://github.com/vulcanize/ops/issues/154)

**Comment by ashwinphatak** [comment]
This legacy API corresponds to the GQL API in geth and can be implemented in the eth-watcher with lazy loading of data.

**Comment by i-norden** [comment]
Pinging here @ashwinphatak for status update on this when you get the chance.

**Comment by ashwinphatak** [comment]
> This legacy API corresponds to the GQL API in geth and can be implemented in the eth-watcher with lazy loading of data.

This is still open (as noted in https://github.com/cerc-io/ipld-eth-server/issues/150#issuecomment-1150881944, should be moved to eth-watcher).

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-server/issues/150
