### ISSUE TITLE
(v5) Add getSlice endpoint for mustekala

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#4]
Spec: https://github.com/paritytech/parity-ethereum/issues/9857

Imp: https://github.com/musteka-la/go-ethereum/commits/wip/slice-sync

Previous WIP: https://github.com/vulcanize/ipld-eth-indexer/commits/actual_getSlice

TODOs:
- [x] Port changes from WIP [branch](https://github.com/vulcanize/ipld-eth-indexer/commits/actual_getSlice)
- [x] Use iterator based approach
- [ ] Performance improvements
- [ ] Add tests

**Comment by prathamesh0** [comment]
@i-norden 
> Previous WIP: https://github.com/vulcanize/ipld-eth-indexer/commits/actual_getSlice

What part of the implementation was remaining in the above branch?

**Comment by i-norden** [comment]
Currently satisfied in https://github.com/cerc-io/ipld-eth-server/pull/206

This needs to be revisited with a higher level discussion about the future of getSlice
