### ISSUE TITLE
Support gasPrice field on dynamicFee transactions

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#80]
https://github.com/ethereum/eth1.0-specs/pull/251

**Comment by i-norden** [comment]
@dboreham @AFDudley pinging since this issue has been buried but is still needed to perfectly replicate the geth eth json rpc api.

We already set gasPrice to effectiveGasPrice for a mined transaction https://github.com/cerc-io/ipld-eth-server/blob/8c55b6341a1cb59c6b641623a8f3527295e45bdc/pkg/eth/backend_utils.go#L200

For an un-mined tx we should adjust so that "If the transaction has not yet been mined, clients should return the maxFeeCapPerGas value as gasPrice". This isn't an issue for us now as we don't have un-mined transactions until we merge the probe database.

**Comment by AFDudley** [comment]
@telackey Please close this if it's been resolved in v5
