### ISSUE TITLE
Update integration tests to test the new Header (with BaseFee) and tx types (access list and dynamic fee)

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#85]
We need to update the test chain we are using to have the new header and txs types present for tests, in https://github.com/vulcanize/ipld-eth-server/tree/master/test/contract

And then we need to update the integration tests to test these new/updated types.

Ref: https://github.com/vulcanize/ipld-eth-server/pull/83#pullrequestreview-716617808

**Comment by AFDudley** [comment]
Superseded by https://github.com/cerc-io/stack-orchestrator
